### ISSUE TITLE
Icons and general content

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#23]

**Comment by rachaeltownley** [comment]
![_afc_icon_rgb_black_body_smiley](https://cloud.githubusercontent.com/assets/28947529/26580054/6103ea72-452e-11e7-9921-54850236310d.png)
![_afc_icon_rgb_black_book](https://cloud.githubusercontent.com/assets/28947529/26580051/61008ad0-452e-11e7-8d86-8e73af7bb8bf.png)
![_afc_icon_rgb_black_clock](https://cloud.githubusercontent.com/assets/28947529/26580050/60ffb3e4-452e-11e7-8907-5f7c0dd58af7.png)
![_afc_icon_rgb_black_contact_mobile](https://cloud.githubusercontent.com/assets/28947529/26580052/61020e0a-452e-11e7-9e6c-7d7233ea8e2b.png)
![_afc_icon_rgb_black_contact_phone](https://cloud.githubusercontent.com/assets/28947529/26580053/61027fac-452e-11e7-8321-f46d8a2ab8b4.png)
![_afc_icon_rgb_black_hand_thumbs](https://cloud.githubusercontent.com/assets/28947529/26580055/61150816-452e-11e7-971d-ae3aa48559f6.png)
![_afc_icon_rgb_black_house](https://cloud.githubusercontent.com/assets/28947529/26580059/611b479e-452e-11e7-86cc-83acb3921090.png)
![_afc_icon_rgb_black_mail](https://cloud.githubusercontent.com/assets/28947529/26580058/6119e034-452e-11e7-8d27-2c9507e74d30.png)
![_afc_icon_rgb_black_moon](https://cloud.githubusercontent.com/assets/28947529/26580057/61184846-452e-11e7-93ca-52d014b4b0fa.png)
![_afc_icon_rgb_black_pencil](https://cloud.githubusercontent.com/assets/28947529/26580056/611802a0-452e-11e7-9752-fefcc9702c61.png)
![_afc_icon_rgb_black_person_disabled](https://cloud.githubusercontent.com/assets/28947529/26580060/61269586-452e-11e7-9f6f-86ad6f657cf4.png)
![_afc_icon_rgb_black_person_man](https://cloud.githubusercontent.com/assets/28947529/26580061/6127f57a-452e-11e7-87a5-d13886852d14.png)
![_afc_icon_rgb_black_person_woman](https://cloud.githubusercontent.com/assets/28947529/26580062/612a1b5c-452e-11e7-83dc-a802d0141b7b.png)
![_afc_icon_rgb_black_petition](https://cloud.githubusercontent.com/assets/28947529/26580063/612d8f08-452e-11e7-962c-71b11c42e813.png)
![_afc_icon_rgb_black_quiz](https://cloud.githubusercontent.com/assets/28947529/26580064/612e8296-452e-11e7-974e-7aea7b5e7a36.png)
![_afc_icon_rgb_black_rel_carer](https://cloud.githubusercontent.com/assets/28947529/26580065/61320d58-452e-11e7-9763-ab612298ae8b.png)
![_afc_icon_rgb_black_rel_parents](https://cloud.githubusercontent.com/assets/28947529/26580066/613b0fca-452e-11e7-8767-de301d3112f0.png)
![_afc_icon_rgb_black_star](https://cloud.githubusercontent.com/assets/28947529/26580067/613bf6b0-452e-11e7-8f16-e8ceeb3b02b9.png)
![_afc_icon_rgb_black_talk](https://cloud.githubusercontent.com/assets/28947529/26580068/613c8cd8-452e-11e7-8e18-03cbd0904299.png)

**Comment by rachaeltownley** [comment]
<img width="476" alt="screen shot 2017-05-30 at 11 57 18" src="https://cloud.githubusercontent.com/assets/28947529/26580253/323d8314-452f-11e7-9750-04b7a0a76df6.png">

**Comment by andrewsprinz** [comment]
Red for headings, links, bars etc #D6001C
#7f7f7f
Body copy: #2d2d2d
Headings: #000000

**Comment by andrewsprinz** [comment]
![logo-main](https://cloud.githubusercontent.com/assets/619374/26580417/f5b13138-452f-11e7-8853-74057d69de62.png)

**Comment by andrewMacmurray** [comment]
👍
