### ISSUE TITLE
Budget 

### ISSUE THREAD

**Issue by ToriCAST** [cast-fuse/action-for-children#30]

**Comment by rachaeltownley** [comment]
https://docs.google.com/spreadsheets/d/1PzyJdDZeSlAnt1_rIQW38UOj1f3f-5igYwXeYRhQuYo/edit#gid=0

Need to find out salary costs for FSWs/BSOs to be able to work out staff costs

**Comment by andrewsprinz** [comment]
Moving non-product tasks to Trello
