### ISSUE TITLE
Add Google Analytics to site for user testing

### ISSUE THREAD

**Issue by andrewsprinz** [cast-fuse/action-for-children#44]
https://action-for-children-staging.herokuapp.com/

Rachael will share the GA code.

Is there any basic Intercom GA event tracking?

**Comment by andrewsprinz** [comment]
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-100560015-1', 'auto');
  ga('send', 'pageview');

</script>`

**Comment by andrewMacmurray** [comment]
closed with pr #48
