### ISSUE TITLE
Redirect logged in users to chat page

### ISSUE THREAD

**Issue by andrewMacmurray** [cast-fuse/action-for-children#49]
when a user is logged in if they visit the landing page they should be redirected to their chat.

> andrews - "just chatted about it, think it’d be good if it auto redirected to the ‘chat’ page if someone is logged in, if that can work?"

**Comment by andrewMacmurray** [comment]
@andrewsprinz yep we can do this

**Comment by ivanmauricio** [comment]
closed via #59
