### ISSUE TITLE
Small design tweaks

### ISSUE THREAD

**Issue by andrewsprinz** [cast-fuse/action-for-children#56]
Have no experience with Elm, but if you guys are busy doing more important things, I'm happy to jump in and tweak the stylesheets then submit a PR.

Otherwise, stuff to fiddle with:

1. Homepage banner image (see attached)
2. Can we do a very simple mobile version, which essentially reflows the two column areas into one column, or in the case of the homepage banner, just removes the background image and makes the text full width?
3. On desktop / tablet can we centre the site context, max width it around 1000px or 90% of the viewport (whatever works, not sure how your grid system works)

![action for children - live chat](https://user-images.githubusercontent.com/619374/26931154-75300730-4c57-11e7-9be0-d7db8d26795c.png)

**Comment by andrewMacmurray** [comment]
sounds good

**Comment by ivanmauricio** [comment]
Btw we're not using Elm on this project, not yet anyway!

**Comment by andrewMacmurray** [comment]
@andrewsprinz I've clipped the image of the lady out for now, and making those changes, do you want the action for children logo to track the edge of the main box?

**Comment by andrewsprinz** [comment]
Yeah that'd be great

**Comment by ivanmauricio** [comment]
closed via #59
