### ISSUE TITLE
required fields on callback page

### ISSUE THREAD

**Issue by andrewMacmurray** [cast-fuse/action-for-children#57]
@andrewsprinz @rachaeltownley should we any of the fields as required on the callback page?

currently we have
+ time of day
+ day
+ topic
+ phone number

We definitely need phone number as required (otherwise they wouldn't be contactable!). We could have the `any` option as selected by default? Or maybe we could assume any if the user doesn't click on anything. What about the time of day and description?

**Comment by andrewMacmurray** [comment]
also we were wondering what you'd like to happen when the user submits the time, do we want to send them to a success screen? Have a popup? Redirect them back to the call page?

**Comment by rachaeltownley** [comment]
@andrewMacmurray @andrewsprinz maybe as well as time of day/day one we could have a 'as soon as possible' option (and if they select this could we have an auto message about if it's urgent or is likely to need medical type attention to contact NHS 111 etc - messaging tbc)

Also I think a successfully submitted option and we can then signpost them to some content to read in the meantime?

**Comment by andrewMacmurray** [comment]
closed with pr #63
