### ISSUE TITLE
Small tweaks for tomorrow

### ISSUE THREAD

**Issue by andrewsprinz** [cast-fuse/action-for-children#64]
Hi Ivan. Not sure how much time you have, but just spoken to Rachael... if you have time, here are a few things we'd like to work through on the test site. In order or priority, realise they won't all be possible for tomorrow!

Grab us on Slack if you'd prefer to chat through.

**Copy tweaks**

Homepage:

1. Typo in last sentence in header on homepage, first word should be "They" (my bad)
2. Change 'Start a conversation' to 'Ask a question'
3. Change copy below 'Start a conversation' to 'You can arrange catch-ups with your parenting expert after you've spoken to them.'

Chat page:

1. Change 'Arrange a call' to to 'Speak to us on the phone', and move this above the "code" paragraph
2. Change button to read: 'Arrange a call'
3. Change "Come back here any time to continue the conversation" to "To speak with your parenting expert again, make a note of this code. You can use it here or if you phone us later."... then display the code in bold below the sentence

**Design tweaks**

1. On chat page, can we make the 'Arrange a call' button to be in the same style as the homepage buttons?
2. Confirmation page for call me back: Can we make this a separate page, with just sub-heading sized text, centred, reading: "We'll text you to arrange a call, we aim to be in touch within 24 hours" 

**Nice to haves**

1. On the homepage, can we add 50px (ish) padding to the bottom of the page
2. On the homepage intro panel, can we increase the line height of subheadings to 1.4
3. Can we change the max width of the .gray text on the homepage panels to 80%, and centre them, and increase line height to 1.5 and bottom margin to 25px

**Comment by ivanmauricio** [comment]
Hi @andrewsprinz, that should be okay, I will make changes this afternoon.

**Comment by ivanmauricio** [comment]
@andrewsprinz I have pushed changes that I have made onto staging. Could you have a look and let me know if that's what you meant, I was a little unsure of exactly where you wanted changes on home screen. I am just moving onto confirmation screen so that is not live yet.

**Comment by andrewsprinz** [comment]
Homepage and chat page look great. Rachael has a quick copy change, sending
that now.

**Comment by ivanmauricio** [comment]
closed via #69
