### ISSUE TITLE
Intercom test app on staging site

### ISSUE THREAD

**Issue by ivanmauricio** [cast-fuse/action-for-children#66]
Hi @andrewsprinz, @rachaeltownley. Andrew and I set up an Intercom test app last week to run our automated tests on (rather than spamming live app). It basically mirrors the live app except the data is kept separate. It may be good to use this for staging site and initial user testing, to keep live app decluttered until it goes live. What do you guys think?

**Comment by andrewsprinz** [comment]
We're going to be using the live app for tomorrow as we have the support workers set up there already and they're testing it. Then after that it makes sense to use the test app for staging!

**Comment by ivanmauricio** [comment]
Sounds good, will move it over after this round of testing.

**Comment by andrewMacmurray** [comment]
@rachaeltownley we've set up the production version at `https://action-for-children.herokuapp.com`, would you be able to point that redirect that you set up for the staging one to the new one? Let me know if that doesn't make sense

**Comment by rachaeltownley** [comment]
@andrewMacmurray I tried updating the url redirect but our CMS seems to have not coped. Will try again tomorrow

**Comment by rachaeltownley** [comment]
@andrewMacmurray there was a problem with our CMS. I deleted and re-set it up :)
