### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#70]
Hi @ivanmauricio can you please change the logo on the site? We don't want the feedback/thoughts from the internal stakeholders to focus on the logo not being right :( as much as the one we've got on there looks better!! Attached (hopefully) is the logo to use instead.
![how afc works logo](https://user-images.githubusercontent.com/28947529/27138785-3956cbf6-5119-11e7-9071-e010108e521a.png)

**Comment by ivanmauricio** [comment]
@rachaeltownley the new logo is on site now :)

**Comment by ivanmauricio** [comment]
Closing via #71
