### ISSUE TITLE
New intercom account?

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#72]
Hiya, a lot of my issues/requests are about more Intercom investigations. Will you need a new Intercom account? If so, let me know and I'll set one up :)

**Comment by andrewMacmurray** [comment]
@rachaeltownley have you guys paid for a new account? If you have we just need the app id and we can link the action for children app with the new account

**Comment by rachaeltownley** [comment]
@andrewMacmurray Not yet, I'll set up a new trial one for 14 days. We have a presentation on the 19th to all the stakeholders (who I basically need the go ahead from to spend money) so until then need to keep doing trials :( If it's ok, I'll set it up tomorrow/Friday then it will be live for that presentation if that's alright? I'll send you the code over

**Comment by andrewMacmurray** [comment]
@rachaeltownley sure, that sounds good, just be aware that all the previous user's chats will be lost as you move over to new accounts

**Comment by rachaeltownley** [comment]
@andrewMacmurray Ooh good point. Worth bearing in mind in case we do more testing pre-pilot :)

**Comment by rachaeltownley** [comment]
@andrewMacmurray @ivanmauricio new Intercom account is set up https://app.intercom.io/invites/6b812c35-cb34-4267-bf68-0f2a31f47f83

**Comment by andrewMacmurray** [comment]
@rachaeltownley awesome thanks ✨ 🦀

**Comment by rachaeltownley** [comment]
@andrewMacmurray I've forgotten how to find the code...is this it j13wvy5o

**Comment by andrewMacmurray** [comment]
@rachaeltownley no worries, just found it, adding it to heroku now

**Comment by andrewMacmurray** [comment]
closing this for now as set up with new account
