### ISSUE TITLE
Paid for tier of Heroku

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#73]
How much is the paid for tier of Heroku? Is it a monthly or one off cost? Thanks :)

**Comment by andrewMacmurray** [comment]
@rachaeltownley here is the pricing for heroku https://www.heroku.com/pricing, it's a monthly cost.

I imagine you'd probably only need the hobby plan, means the app won't go to "sleep" (i.e. when no one has visited the app for 30mins there's about a 5-8s wait when the next user accesses the site).

Was there any particular reason you were thinking about the paid for heroku plans?

**Comment by rachaeltownley** [comment]
Andrew had suggested it because we don't want the pilot etc to be about slow loading speeds etc. And when we're demoing it.

$7 a month doesn't sound too shabby, I'll check with Lynn :)

**Comment by andrewMacmurray** [comment]
@rachaeltownley cool, if you get the go ahead we'll need some card details to add to the heroku account and we can upgrade it

**Comment by rachaeltownley** [comment]
@andrewMacmurray have got the go ahead for Heroku. Not sure what the most secure way of me sending you my card details are? Slack????

**Comment by andrewMacmurray** [comment]
@rachaeltownley yea slack is probably best 👍

**Comment by andrewMacmurray** [comment]
just to add from our conversation in slack: I'm thinking we should probably transfer the account ownership over to you @rachaeltownley or action for children so the billing doesn't get mixed up with other things from the CAST heroku account

**Comment by rachaeltownley** [comment]
Card details sent to Ivan. Ivan also going to try and transfer account ownership to me :)

**Comment by rachaeltownley** [comment]
@andrewMacmurray Heroku account set up. Log in deets....
Username: rachael.townley@actionforchildren.org.uk
Password: castfuse!

**Comment by andrewMacmurray** [comment]
@rachaeltownley great, make sure you change your password though and pm me the details (this is a public page lol)

**Comment by rachaeltownley** [comment]
@andrewMacmurray oooopsy, will slack you

**Comment by andrewMacmurray** [comment]
@rachaeltownley thanks for setting this all up, when you're ready to start the pilot we can switch on one of the paid for dynos (things that make it run faster) 👍
