### ISSUE TITLE
Investigate/implement ability to edit names and email addresses for parents

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#74]
For the FSW to be able to do on the user's profile in the back end of Intercom

**Comment by andrewMacmurray** [comment]
@rachaeltownley is there no where the FSW can do this on the dashboard?

**Comment by ivanmauricio** [comment]
@rachaeltownley This cannot be done on the admin interface. I looked into this when we were doing our Intercom research. The only way to update a user is via their API or by uploading a CSV. Both of these solutions require some technical knowledge so it is not something that FSW could do. One possibility is building an admin interface to be able to do this, however this would be a big piece which would take some time.

**Comment by andrewMacmurray** [comment]
Yea I remember now this being a bit of a pain, as a workaround is there a way you could use tags to identify a user? I know it's not ideal but could work in the interim

**Comment by rachaeltownley** [comment]
@andrewMacmurray @ivanmauricio aaah ok. Maybe the tags or the notes/comments bit? Once I've set up the new trial account on Friday I'll give both of these options a go :)
