### ISSUE TITLE
Investigate how we can secure the 'chat' page so that it can not be accidentally shared

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#75]

**Comment by andrewMacmurray** [comment]
@rachaeltownley so one of the tradeoffs with having the "user code" style login is that it doesn't require a password, we'd need user accounts if we wanted to secure the chat page, is this worth doing for the pilot or something we'd like to implement in the future?

**Comment by andrewMacmurray** [comment]
the bottom line is we'd loose the fluid user experience we have at the moment if we were to ask a new user to sign up

**Comment by rachaeltownley** [comment]
I think for the pilot we could leave it? As there will be a lot of these sorts of questions/requirements I imagine once we have done the pilot and when safeguarding/data really get involved

**Comment by andrewMacmurray** [comment]
@rachaeltownley I think that sounds like a good idea, definitely something worth keeping in mind for re-thinking security / user experience requirements

**Comment by andrewMacmurray** [comment]
closing this for now, can reopen after the pilot phase
