### ISSUE TITLE
Auto responses within the chat

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#76]
Ensure that the prompt for email/SMS always appears (if no reply from FSW for a minute?)

**Comment by andrewMacmurray** [comment]
@rachaeltownley will have a look at this

**Comment by andrewMacmurray** [comment]
as far as where we'd got to with the auto responses, I think there's a default response if no one is online but will have to check. Do you know if one came up at any point?

**Comment by ivanmauricio** [comment]
@rachaeltownley @andrewMacmurray There is an option on Intercom for choosing how quickly the team is likely to respond. If this is set to a couple of hours then the email/phone capture form comes up after 2 minutes of the user sending a message.

**Comment by ivanmauricio** [comment]
Just a correction on the above, the form comes up after 2 minutes if the respond time is 'a few minutes'. If it is 'a few hours' then it comes up quicker than this, I haven't found out exactly how quickly though.

**Comment by rachaeltownley** [comment]
@andrewMacmurray @ivanmauricio we didn't have anyone use it whilst the staff were offline. But we did have an instance where a support worker was online but was busy with another parent. So the second parent was left for the 15 minutes it took for the FSW to finish with the other parent. There was no message for her though I don't think?

**Comment by rachaeltownley** [comment]
I think we probably need the message to come up fairly quickly as 2 minutes would probably feel like quite a long time. Could we set it as a few hours so that t he message comes up quickly? Then we can test what the perception of seeing 'responds within a few hours' does to the parent?

**Comment by andrewMacmurray** [comment]
@rachaeltownley ok that makes sense, may be worth playing around with it to get it right

**Comment by andrewMacmurray** [comment]
@rachaeltownley been having chatty chats with intercom peoples and they have suggested a good solution to get this to work.

Currently when a not signed in user goes from the home page to the chat page, behind the scenes they are created as a new intercom user. This means that they won't see the popup (intercom assumes that if you're making a new user then you must have their email address already).

We might be able to set the new user up as a "lead" (i.e. someone who hasn't "signed up"), but will have to rethink how we do the behind the scenes stuff to make this work.

I have some time next week to do this so will draft out a plan today

**Comment by rachaeltownley** [comment]
@andrewMacmurray @ivanmauricio ooh sounds good! Did you get a chance to draft a plan? Sorry for my insanely slow reply :(
