### ISSUE TITLE
Investigate incoming and outgoing email addresses for Intercom

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#77]

**Comment by andrewMacmurray** [comment]
@rachaeltownley I'm not sure I understand what you mean by this, could you give a bit more detail?

**Comment by rachaeltownley** [comment]
@andrewMacmurray when we email users to confirm a call time, or to let them know that someone is online and available to chat now etc, what's the email address that it appears as in their inbox? And can this be changed? If you need an email for now to try it, you can use digital@actionforchildren.org.uk and then once we have something decided for it we can change it to something for the actual service?

**Comment by andrewMacmurray** [comment]
@rachaeltownley ok that makes sense, let us know when you've set up the next trial account and we can test it out

links #72

**Comment by andrewMacmurray** [comment]
@rachaeltownley I've added the digital@actionforchildren.org.uk email to the list of outbound email responses, intercom has sent an email to it so you'll just have to click on the link to verify it

**Comment by andrewMacmurray** [comment]
@rachaeltownley any update on this?

**Comment by rachaeltownley** [comment]
@andrewMacmurray I _think_ I verified it? Is it showing up as not?

**Comment by andrewMacmurray** [comment]
@rachaeltownley what's the link again?

**Comment by andrewMacmurray** [comment]
lol sorry wrong issue 😆 , that's good then
