### ISSUE TITLE
Homepage tweaks

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#79]
@andrewMacmurray @ivanmauricio 

How easy would it be to make some changes to the heroku site? I'll send through designs/suggestions and could you let me know whether you could do them? (Ideally by the end of tomorrow but realise that it SUPER short notice)

**Comment by rachaeltownley** [comment]
![homepage](https://user-images.githubusercontent.com/28947529/28270818-af8c9db0-6afe-11e7-93f5-83d5b7a3a1b3.jpg)

Is it possible to make change the homepage to the attached (with the box on the left linking to a new page - content to be supplied

**Comment by rachaeltownley** [comment]
![meet our experts](https://user-images.githubusercontent.com/28947529/28272572-cf7dd5bc-6b03-11e7-91ef-2dfdafc21b13.jpg)

Our experts page...copy for now....
Our parent experts have all worked in children's centres and have been helping parents and families for many years.  You can ask our experts absolutely anything about parenting and we will support you with advice specific to your situation.  It can be about development, behaviour, feeding, family life, wellbeing, understanding your child, sleeping, etc. We really don’t mind what you want to ask us about, we are here to help you.  Meet Louise I have been a Family Support Worker for 6 years and have run young parent groups, stay and play, infant massage, breastfeeding clinics, parenting courses and supported children and families in the home.  I am passionate about children reaching their full potential and having the chance to thrive and I hope in some small way I contribute towards this.  I hope that I can continue to support parents and families and look forward to meeting more amazing families along the way.

**Comment by rachaeltownley** [comment]
![talk to expert](https://user-images.githubusercontent.com/28947529/28272731-4a27f392-6b04-11e7-9d1c-6e0dd2602bc0.jpg)

Talk to an expert page tweaks

Copy...
How to talk to us
You can ask us any parenting or family question, but so that we can help you please provide as much context as you are comfortable with.

For example, if you need advice around your child's sleeping, let us know their age and bedtime routine. This means we can give you really tailored advice.

You can use the online chat to the right and one of our experts will get back to you as soon as possible. If no-one is available straight away you can fill in your email address and you'll be notified when someone is available to talk to you.

Speak to us on the phone
If you'd rather speak to one of our experts on the phone, you can arrange a time for us to call you.   

Speak to us again
To speak to the same parenting expert again and carry on our conversation, make a note of the 8 digit code below.

You can use this code for online chat or on the phone.

**Comment by ivanmauricio** [comment]
@rachaeltownley will do my best to get it done before tomorrow afternoon!

**Comment by rachaeltownley** [comment]
@ivanmauricio You're a legend, I'll keep an eye on slack/github today in case you have any questions about my garbled content :)

**Comment by rachaeltownley** [comment]
Ivan is a hero
