### ISSUE TITLE
Add a banner

### ISSUE THREAD

**Issue by rachaeltownley** [cast-fuse/action-for-children#81]
Hello, could you please add some sort banner across the bottom of the homepage (and probably the talk to an expert page) that says "This service isn't available 24/7. If your question is urgent, or medical or you are worried about a child please contact the appropriate emergency service or organisation."

Thanks :)

**Comment by andrewMacmurray** [comment]
@rachaeltownley ok, we can add some text to the bottom of both pages. For future though let's save adding things like these for sprint planning, otherwise this kind of thing can very quickly turn into feature creep.
